# Generated by Django 5.2.1 on 2025-05-10 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tablerestaurant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_reservation',
            field=models.CharField(choices=[('hotel', 'Hôtel'), ('restaurant', 'Restaurant')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
