# Generated by Django 5.2.1 on 2025-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reservation_table_reservation_type_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paiement_effectue',
            field=models.BooleanField(default=False),
        ),
    ]
