# Generated by Django 5.1.7 on 2025-05-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reservation_paiement_effectue'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.reservation'),
            preserve_default=False,
        ),
    ]
