# Generated by Django 5.1.7 on 2025-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paiement_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerestaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tables/'),
        ),
        migrations.AlterField(
            model_name='tablerestaurant',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
