# Generated by Django 5.1.7 on 2025-05-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_demandegerant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='services',
            field=models.ManyToManyField(blank=True, to='accounts.servicesupplementaire'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='superficie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
