# Generated by Django 5.1.7 on 2025-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
