# Generated by Django 5.1.7 on 2025-05-29 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_menu_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='reservation',
        ),
        migrations.AddField(
            model_name='avis',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avis',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.etablissement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveIntegerField(),
        ),
    ]
