# Generated by Django 5.1.7 on 2025-05-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_avis_reservation_avis_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='type_gerant',
            field=models.CharField(blank=True, choices=[('hotel', 'Hôtel'), ('restaurant', 'Restaurant')], max_length=20, null=True),
        ),
    ]
